server:
  port: 8070

eureka:
  instance:
    hostname:
      hostname: localhost
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl: http://${eureka.instance.hostname}:${server.port}/eureka/

