
build:
  version: "1.1"

loans:
  message: "Welcome to LnBanking loans services API(dev)"
  contactDetails:
    name: "Luciano devs - Developer"
    email: "lucianodevs@lnbanking.com"
  onCallSupport:
    - (000) 000 000
    - (000) 000 001
